"""added foreign keys

Revision ID: 0a100e122959
Revises: 9addb44af38d
Create Date: 2020-10-26 14:02:33.307166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a100e122959'
down_revision = '9addb44af38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'attempts', 'problems', ['problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    # ### end Alembic commands ###
