"""empty message

Revision ID: a95d9141f57b
Revises: 2575957d3c58
Create Date: 2020-10-28 14:49:26.651545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95d9141f57b'
down_revision = '2575957d3c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('call', sa.String(), nullable=False),
    sa.Column('expected', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('problems', 'tests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('tests', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('tests')
    # ### end Alembic commands ###
