"""tests_table

Revision ID: df95500874eb
Revises: 2575957d3c58
Create Date: 2020-10-27 16:06:44.812111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df95500874eb'
down_revision = '2575957d3c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('call', sa.String(), nullable=False),
    sa.Column('expected', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('problems', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('problems', 'tests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('tests', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('problems', 'category')
    op.drop_table('tests')
    # ### end Alembic commands ###
